@startuml
    ' REFERENCE: https://isgb.otago.ac.nz/infosci/INFO202/reference/raw/master/reference.html#Sequence%20Diagrams:Contents%20%5B%5BSequence%20Diagrams%5D%5D

    ' use strict UML mode
    skinparam style strictuml

    actor "User" as user
    participant "Administration" as main <<main>>
    main++

    create "FrameMainMenu" as menu <<frame>>

    main -> menu : construct
    
    user -> menu++ : click 'add a new product'
    
    create "DialogProductEditor" as editor <<dialog>>
    menu -> editor : construct

    ' activate editor constructor
    editor++
        ' create a DAO
        create "DAO" as dao <<dao>>
        editor -> dao++ : construct

        editor -> dao : getCategories() : categories
        dao--

        create "SimpleListModel : listModel" as listModel <<model>>
        editor -> listModel : construct(categories)
        editor -> editor : set combo box model (listModel)

        editor--

    ' user enters product details and clicks the save button
    user -> editor++ : enters product details
        editor--
    user ->  editor++ : click 'save' button
        editor -> editor : get product details from GUI components

        editor -> editor : convert numeric fields to BigDecimal and Integer types

        ' construct the product object
        create "Product : product" as product <<domain>>
        editor -> product : construct

        ' set the fields in the product
        editor -> product++ : set product details
            product--

        ' save product
        editor -> dao++ : saveProduct(product)
            dao--

        ' dispose dialog
        editor -> editor : dispose()
        destroy editor
        editor--
        
    ' user closes the dialog
    user -> editor++ : click 'cancel' button / closes dialog
        ' dispose dialog
        editor -> editor : dispose()
        destroy editor
        menu--
        
    user -> menu++ : click 'exit' button
    menu -> menu : System.exit(0)
    destroy menu
    main--

    
@enduml
