package gui;

import dao.DAOException;
import domain.Product;
import gui.helpers.SimpleListModel;
import gui.helpers.ValidationHelper;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import dao.ProductDAO;

/**
 *
 * @author docma436
 */
public class DialogViewProducts extends javax.swing.JDialog {

    private SimpleListModel listModel; // List model for list view.
    private SimpleListModel listModelCategories; // List model for filter combo box.
    
    private final ProductDAO dao;
    
    private ValidationHelper validHelp;

    /**
     * Creates new form DialogViewProducts
     */
    public DialogViewProducts(java.awt.Frame parent, boolean modal, ProductDAO dao) {
        super(parent, modal);
        initComponents();

        this.dao = dao;
        
        try {
            listModel = new SimpleListModel(dao.getProducts());
            listProducts.setModel(listModel);

            listModelCategories = new SimpleListModel(dao.getCategories());
            comboBoxFilter.setModel(listModelCategories);

            buttonReset.setEnabled(false);

            // Pressing enter in search text field to search.
            txtSearch.addActionListener(al -> {
                buttonSearch.doClick();
            });
            
            validHelp = new ValidationHelper();
            validHelp.addPatternFormatter(txtSearch, Pattern.compile("((^[A-Za-z]{0,2})|(^[A-Za-z]{2}[0-9]{0,4}))"),
                    "Product IDs consist of a 2 letter prefix and a 4 digit suffix. E.g. AB1234");

        } catch (DAOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "DAO Exception", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPaneProducts = new javax.swing.JScrollPane();
        listProducts = new javax.swing.JList<>();
        buttonClose = new javax.swing.JButton();
        labelSearch = new javax.swing.JLabel();
        labelFilter = new javax.swing.JLabel();
        comboBoxFilter = new javax.swing.JComboBox<>();
        buttonSearch = new javax.swing.JButton();
        buttonEdit = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        buttonReset = new javax.swing.JButton();
        txtFilterDetails = new javax.swing.JLabel();
        txtSearch = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("View Products");

        listProducts.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listProducts.setName("listProducts"); // NOI18N
        scrollPaneProducts.setViewportView(listProducts);

        buttonClose.setText("Close");
        buttonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCloseActionPerformed(evt);
            }
        });

        labelSearch.setText("Search by ID:");

        labelFilter.setText("Category Filter:");

        comboBoxFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxFilterActionPerformed(evt);
            }
        });

        buttonSearch.setText("Search");
        buttonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchActionPerformed(evt);
            }
        });

        buttonEdit.setText("Edit");
        buttonEdit.setName("buttonEdit"); // NOI18N
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });

        buttonDelete.setText("Delete");
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        buttonReset.setText("View All");
        buttonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResetActionPerformed(evt);
            }
        });

        txtFilterDetails.setFont(new java.awt.Font("Noto Sans", 0, 10)); // NOI18N
        txtFilterDetails.setForeground(java.awt.Color.gray);
        txtFilterDetails.setText("Showing all products");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelFilter, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelSearch, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboBoxFilter, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(scrollPaneProducts, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                .addGap(12, 12, 12))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21)
                .addComponent(buttonDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21)
                .addComponent(buttonClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtFilterDetails)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSearch)
                    .addComponent(buttonSearch)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFilter)
                    .addComponent(comboBoxFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonReset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFilterDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneProducts, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonClose)
                    .addComponent(buttonEdit)
                    .addComponent(buttonDelete))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCloseActionPerformed
        dispose();
    }//GEN-LAST:event_buttonCloseActionPerformed

    private Product getSelectedProduct() {
        // Ensure we only proceed if there is a selection from the list.
        if (listProducts.isSelectionEmpty()) {
            return null;
        }

        return (Product) listProducts.getSelectedValue();
    }

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        Product product;
        if ((product = getSelectedProduct()) == null) {
            return;
        }

        // Show confirmation dialog
        int result = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete product "
                + product + "?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            try {
                dao.deleteProduct(product);
                listModelCategories.updateItems(dao.getCategories());
                comboBoxFilter.setSelectedItem(null);
                txtSearch.setText("");
                listModel.updateItems(dao.getProducts());
                buttonReset.setEnabled(false);
                txtFilterDetails.setText("Showing all products");
            } catch (DAOException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "DAO Exception", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
        Product product;
        if ((product = getSelectedProduct()) == null) {
            return;
        }

        DialogProductEditor dialog = new DialogProductEditor(this, true, product, dao);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);

        try {
            listModelCategories.updateItems(dao.getCategories());
            comboBoxFilter.setSelectedItem(null);
            txtSearch.setText("");
            listModel.updateItems(dao.getProducts());
            buttonReset.setEnabled(false);
            txtFilterDetails.setText("Showing all products");
        } catch (DAOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "DAO Exception", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonEditActionPerformed

    private void buttonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchActionPerformed
        String search = txtSearch.getText();

        if (search.equals("")) {
            buttonReset.doClick();
            return;
        }

        try {
            Product searchResult = dao.getProductByID(search);

            comboBoxFilter.setSelectedItem(null);
            listModel.updateItems(searchResult);
            txtSearch.setText(search); // Restore search text which was deleted by combo box event handler.
            buttonReset.setEnabled(true);

            txtFilterDetails.setText("Showing products with id '" + search + "'");
        } catch (DAOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "DAO Exception", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonSearchActionPerformed

    private void comboBoxFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxFilterActionPerformed
        try {
            listModel.updateItems(dao.getProductsByCategory(String.valueOf(comboBoxFilter.getSelectedItem())));
            buttonReset.setEnabled(true);
            txtSearch.setText("");
            txtFilterDetails.setText("Showing products in category '"
                    + String.valueOf(comboBoxFilter.getSelectedItem()) + "'");
        } catch (DAOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "DAO Exception", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_comboBoxFilterActionPerformed

    private void buttonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResetActionPerformed
        try {
            comboBoxFilter.setSelectedItem(null);
            txtSearch.setText("");
            listModel.updateItems(dao.getProducts());
            buttonReset.setEnabled(false);
            txtFilterDetails.setText("Showing all products");
        } catch (DAOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "DAO Exception", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonResetActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClose;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonReset;
    private javax.swing.JButton buttonSearch;
    private javax.swing.JComboBox<String> comboBoxFilter;
    private javax.swing.JLabel labelFilter;
    private javax.swing.JLabel labelSearch;
    private javax.swing.JList<Product> listProducts;
    private javax.swing.JScrollPane scrollPaneProducts;
    private javax.swing.JLabel txtFilterDetails;
    private javax.swing.JFormattedTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
